# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  极客玩家Bravo Yeung
subtitle: 爱生活，爱技术
name: Bravo Yeung
email: yanglr@126.com
description: 本站是极客玩家Bravo Yeung的技术分享博客。内容涵盖 .NET开发, PHP开发, 算法面试题等等~
keywords: geekplayer, geekplayers, 极客玩家, .NET, C#, .NET Core,PHP,RSS,k8s,生活故事,一线,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客, .NET,Python,
encoding: "utf-8"
favicon: favicon.ico

repository: yanglr/yanglr.github.io
github_url: https://github.com/yanglr
url: http://geekplayers.com
enforce_ssl: https://geekplayers.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /python.html
    label: Python  
    target: _self

  -
    href: /it.html
    label: IT
    target: _self

  -
    href: /zsxq.html
    label: 星球
    target: _self   

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self


# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    
    href: /dotnet.html
    label: .NET
    target: _blank
    subnav:

      -
        subHref: /csharp.html
        subLabel: "C#"

      -
        subHref: /wpf.html
        subLabel: WPF
        
      -
        subHref: http://enjoy233.cnblogs.com
        subLabel: .NET 极客技术
        target: _blank

  -
    href: /algo.html
    label: 算法
    target: _self

  -
    href: /k8s.html
    label: k8s
    target: _self
    subnav:

      -        
        subHref: /k8s.html
        subLabel: k8s

  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /docker.html
    label: Docker
    target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /geektime.html
    label: 极客
    target: _blank


# selected articles
classes:

  -
    href: /life.html
    name: 我的生活
    describe: 

  -
    href: /dotnet.html
    name: .NET 系列文章
    describe: 


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [.NET, MySQL, Oracle, Design Patterns]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, vue, xamarin]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: yanglr
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yanglr
    repo: blog-comments
    oauth:
        client_id: 22eb6462c987e7a79860  # owner: yanglr
        client_secret: 6cd15fa90d4e2f73fa16eaab9b3f783831fe3f3d
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yanglr
    repo: blog-comments
    clientID: 22eb6462c987e7a79860  # owner: yanglr
    clientSecret: 6cd15fa90d4e2f73fa16eaab9b3f783831fe3f3d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

simple_jekyll_search:
     # 是否支持全文搜索
     fulltext: false
     # 最多显示多少条搜索结果
     limit: 10